# Generated by Django 5.1.4 on 2025-03-08 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blogpage_remove_blogindexpage_intro_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
