# Generated by Django 5.1.4 on 2025-03-08 03:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
